[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.pylint.messages_control]
disable = ["W0312", "C0330", "C0103", "locally-disabled"]

[tool.pylint.format]
max-line-length = 160
